---
title: "Programa de Prevención & Control del Dengue | 2024"
format: 
  dashboard:
      scrolling: true
      logo: https://www.gob.mx/cms/uploads/action_program/main_image/26942/post_post_portadavectores.gif
      nav-buttons: [twitter, github, facebook]
theme: custom.scss
---

```{r setup}
library(sf)
mapview::mapviewOptions(default = TRUE,
                        basemaps.color.shuffle = FALSE)
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
load("/Users/felipedzul/Library/CloudStorage/OneDrive-Personal/proyects/geocoding_mex/2024/8.RData/denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("D:\\OneDrive\\proyects\\geocoding_mex\\2024\\8.RData\\denmex_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    
}
library(magrittr)
```



# [**Cadenas de Transmisión**]{style="font-size:8pt"}

::: panel-tabset

### [**Veracruz**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "30",
                                     locality = c("Veracruz", "Boca del Rio"),
                                     dengue_cases = "Confirmado")
```


### [**Xalapa**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "30",
                                     locality = "Xalapa de Enriquez",
                                     dengue_cases = "Confirmado")

```



### [**Coatzacoalcos**]{style="color:#990000"}

```{r}
denhotspots::transmission_chains_map(geocoded_dataset = z,
                                     cve_edo = "30",
                                     locality = c("Coatzacoalcos",
                                                  "Puerto Esmeraldas",
                                                  "Fraccionamiento Ciudad Olmecas",
                                                  "Allende",
                                                  "Lomas de Barrandillas"),
                                     dengue_cases = "Confirmado")
```


:::



# [**Mapas de Calor**]{style="font-size:8pt"}

::: panel-tabset

### [**Veracruz**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "30",
                   locality = "Veracruz",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```


### [**Xalapa**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "30",
                   locality = "Xalapa de Enriquez",
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```

### [**Coatzacoalcos**]{style="color:#990000"}

```{r}
densnv::mp_heatmap(geocoded_datasets = z,
                   cve_edo = "30",
                   locality = c("Coatzacoalcos",
                                "Puerto Esmeralda"),
                   status_caso = c(1, 2),
                   week = c(1:53),
                   zoom = NULL,
                   map_type = NULL,
                   alpha = 0.6,
                   static = FALSE,
                   palette = viridis::turbo)
```

:::


# [**Log-Gaussian Cox Processes**]{style="font-size:8pt"}

::: panel-tabset

### [**Veracruz**]{style="color:#990000"}

```{r}
if(as.vector(Sys.info()["sysname"]) == "Darwin"){
    load("~/Dropbox/r_developments/r_dashboards/netlify/transmission_chains/transmission_chains_2024/lgcp_veracruz_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("C:\\Users\\Felipe\\Dropbox\\r_developments\\r_dashboards\\netlify\\transmission_chains\\transmission_chains_2024\\lgcp_veracruz_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    
}

lgcp_veracruz_2024$map
```


### [**Xalapa**]{style="color:#990000"}

```{r}

if(as.vector(Sys.info()["sysname"]) == "Darwin"){
    load("~/Dropbox/r_developments/r_dashboards/netlify/transmission_chains/transmission_chains_2024/lgcp_xalapa_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("C:\\Users\\Felipe\\Dropbox\\r_developments\\r_dashboards\\netlify\\transmission_chains\\transmission_chains_2024\\lgcp_xalapa_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    
}

lgcp_xalapa_2024$map
```

### [**Coatzacoalcos**]{style="color:#990000"}

```{r}

if(as.vector(Sys.info()["sysname"]) == "Darwin"){
    load("~/Dropbox/r_developments/r_dashboards/netlify/transmission_chains/transmission_chains_2024/lgcp_coatza_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Windows"){
   load("C:\\Users\\Felipe\\Dropbox\\r_developments\\r_dashboards\\netlify\\transmission_chains\\transmission_chains_2024\\lgcp_coatza_2024.RData")
} else if(as.vector(Sys.info()["sysname"]) == "Linux"){
    
}

lgcp_coatza_2024$map
```


:::

